# Generated by Django 4.0.3 on 2022-03-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captureAttendance', '0003_remove_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
