# Generated by Django 4.0.3 on 2022-03-29 17:34

import captureAttendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captureAttendance', '0004_image_created_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to=captureAttendance.models.path_and_rename)),
                ('name', models.TextField(default='DEFAULT')),
                ('empId', models.TextField(default='DEFAULT')),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
