# Generated by Django 4.0.3 on 2022-04-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captureAttendance', '0007_admin_superadmin_employee_email_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
