# Generated by Django 4.0.3 on 2022-04-28 21:11

import captureAttendance.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('captureAttendance', '0009_user_delete_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('companyId', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('image', models.ImageField(null=True, upload_to=captureAttendance.models.path_and_rename)),
                ('city', models.TextField()),
                ('country', models.TextField()),
                ('isApproved', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SuperAdmin',
        ),
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.FileField(null=True, upload_to=captureAttendance.models.path_and_rename),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.TextField(default='DEFAULT_Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='empId',
            field=models.TextField(unique=True),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AddField(
            model_name='user',
            name='companyId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='captureAttendance.company', to_field='companyId'),
            preserve_default=False,
        ),
    ]
