# Generated by Django 4.0.3 on 2022-04-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captureAttendance', '0010_company_delete_superadmin_user_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
