# Generated by Django 4.0.3 on 2022-04-29 12:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('captureAttendance', '0012_alter_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='empId',
            new_name='userId',
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.TextField(choices=[('CI', 'CheckIn'), ('CO', 'CheckOut')])),
                ('datetime', models.DateTimeField()),
                ('location', models.TextField()),
                ('companyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captureAttendance.company', to_field='companyId')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captureAttendance.user', to_field='userId')),
            ],
        ),
    ]
