# Generated by Django 4.0.3 on 2022-04-30 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captureAttendance', '0014_rename_logs_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='username',
        ),
    ]
