# Generated by Django 4.0.3 on 2022-04-30 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captureAttendance', '0015_rename_email_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='email',
        ),
    ]
