# Generated by Django 4.0.3 on 2022-05-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captureAttendance', '0017_alter_company_companyid_alter_user_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companyId',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(null=True),
        ),
    ]
