# Generated by Django 4.0.3 on 2022-05-01 21:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('captureAttendance', '0018_alter_company_companyid_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companyId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
