# Generated by Django 4.0.3 on 2022-05-01 21:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('captureAttendance', '0019_alter_company_companyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companyId',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
