# Generated by Django 4.0.3 on 2022-05-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captureAttendance', '0020_alter_company_companyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companyId',
            field=models.TextField(unique=True),
        ),
    ]
