# Generated by Django 4.0.3 on 2022-05-02 07:21

import captureAttendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captureAttendance', '0025_alter_log_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(null=True, upload_to=captureAttendance.models.path_and_rename_company),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to=captureAttendance.models.path_and_rename_user),
        ),
    ]
